monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-XiiSound_Technology_Corporation_Temple_V2-00"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true,
        api.alsa.ignore-dB = true
      }
    }
  }
]
